/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Listing {
  'id' : string,
  'title' : string,
  'description' : string,
  'seller' : Principal,
  'timestamp' : Time,
  'category' : ListingCategory,
  'price' : bigint,
  'location' : string,
  'condition' : ListingCondition,
  'images' : Array<ExternalBlob>,
}
export type ListingCategory = { 'watches' : null } |
  { 'earphones' : null } |
  { 'macbooks' : null } |
  { 'phones' : null };
export type ListingCondition = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'likeNew' : null };
export interface Message {
  'id' : string,
  'content' : string,
  'listingId' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface PickupBooking {
  'id' : string,
  'status' : PickupBookingStatus,
  'date' : string,
  'sellerName' : string,
  'address' : string,
  'timestamp' : Time,
  'phone' : string,
  'quotedPrice' : bigint,
  'timeSlot' : string,
  'deviceModel' : string,
}
export type PickupBookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'isVerified' : boolean,
  'aadhaarHash' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<[Listing], string>,
  'deleteListing' : ActorMethod<[string], undefined>,
  'filterByCategory' : ActorMethod<[ListingCategory], Array<Listing>>,
  'filterByCondition' : ActorMethod<[ListingCondition], Array<Listing>>,
  'filterByPriceRange' : ActorMethod<[bigint, bigint], Array<Listing>>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getAllListingsByPrice' : ActorMethod<[], Array<Listing>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllPickupBookings' : ActorMethod<[], Array<PickupBooking>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getCallerRelatedListings' : ActorMethod<[], Array<Listing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListingById' : ActorMethod<[string], [] | [Listing]>,
  'getMessagesForListing' : ActorMethod<[string], Array<Message>>,
  'getPickupBooking' : ActorMethod<[string], [] | [PickupBooking]>,
  'getPickupsByDate' : ActorMethod<[string], Array<PickupBooking>>,
  'getPickupsByStatus' : ActorMethod<
    [PickupBookingStatus],
    Array<PickupBooking>
  >,
  'getPickupsByTimeSlot' : ActorMethod<[string], Array<PickupBooking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postMessage' : ActorMethod<[string, Principal, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListings' : ActorMethod<[string], Array<Listing>>,
  'submitPickupBooking' : ActorMethod<[PickupBooking], string>,
  'updateBookingStatus' : ActorMethod<[string, PickupBookingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];