/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ListingCategory = IDL.Variant({
  'watches' : IDL.Null,
  'earphones' : IDL.Null,
  'macbooks' : IDL.Null,
  'phones' : IDL.Null,
});
export const ListingCondition = IDL.Variant({
  'new' : IDL.Null,
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'likeNew' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Listing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'timestamp' : Time,
  'category' : ListingCategory,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'condition' : ListingCondition,
  'images' : IDL.Vec(ExternalBlob),
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'listingId' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const PickupBookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PickupBooking = IDL.Record({
  'id' : IDL.Text,
  'status' : PickupBookingStatus,
  'date' : IDL.Text,
  'sellerName' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'quotedPrice' : IDL.Nat,
  'timeSlot' : IDL.Text,
  'deviceModel' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'isVerified' : IDL.Bool,
  'aadhaarHash' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func([Listing], [IDL.Text], []),
  'deleteListing' : IDL.Func([IDL.Text], [], []),
  'filterByCategory' : IDL.Func(
      [ListingCategory],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'filterByCondition' : IDL.Func(
      [ListingCondition],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'filterByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllListingsByPrice' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllPickupBookings' : IDL.Func([], [IDL.Vec(PickupBooking)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getCallerRelatedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListingById' : IDL.Func([IDL.Text], [IDL.Opt(Listing)], ['query']),
  'getMessagesForListing' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getPickupBooking' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PickupBooking)],
      ['query'],
    ),
  'getPickupsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PickupBooking)],
      ['query'],
    ),
  'getPickupsByStatus' : IDL.Func(
      [PickupBookingStatus],
      [IDL.Vec(PickupBooking)],
      ['query'],
    ),
  'getPickupsByTimeSlot' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PickupBooking)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postMessage' : IDL.Func([IDL.Text, IDL.Principal, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'submitPickupBooking' : IDL.Func([PickupBooking], [IDL.Text], []),
  'updateBookingStatus' : IDL.Func([IDL.Text, PickupBookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ListingCategory = IDL.Variant({
    'watches' : IDL.Null,
    'earphones' : IDL.Null,
    'macbooks' : IDL.Null,
    'phones' : IDL.Null,
  });
  const ListingCondition = IDL.Variant({
    'new' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'likeNew' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Listing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'timestamp' : Time,
    'category' : ListingCategory,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'condition' : ListingCondition,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'listingId' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const PickupBookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PickupBooking = IDL.Record({
    'id' : IDL.Text,
    'status' : PickupBookingStatus,
    'date' : IDL.Text,
    'sellerName' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'quotedPrice' : IDL.Nat,
    'timeSlot' : IDL.Text,
    'deviceModel' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'isVerified' : IDL.Bool,
    'aadhaarHash' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func([Listing], [IDL.Text], []),
    'deleteListing' : IDL.Func([IDL.Text], [], []),
    'filterByCategory' : IDL.Func(
        [ListingCategory],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'filterByCondition' : IDL.Func(
        [ListingCondition],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'filterByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllListingsByPrice' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllPickupBookings' : IDL.Func([], [IDL.Vec(PickupBooking)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getCallerRelatedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListingById' : IDL.Func([IDL.Text], [IDL.Opt(Listing)], ['query']),
    'getMessagesForListing' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getPickupBooking' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PickupBooking)],
        ['query'],
      ),
    'getPickupsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PickupBooking)],
        ['query'],
      ),
    'getPickupsByStatus' : IDL.Func(
        [PickupBookingStatus],
        [IDL.Vec(PickupBooking)],
        ['query'],
      ),
    'getPickupsByTimeSlot' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PickupBooking)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postMessage' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
    'submitPickupBooking' : IDL.Func([PickupBooking], [IDL.Text], []),
    'updateBookingStatus' : IDL.Func([IDL.Text, PickupBookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };