/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface PickupBooking {
    id: string;
    status: PickupBookingStatus;
    date: string;
    sellerName: string;
    address: string;
    timestamp: Time;
    phone: string;
    quotedPrice: bigint;
    timeSlot: string;
    deviceModel: string;
}
export interface Listing {
    id: string;
    title: string;
    description: string;
    seller: Principal;
    timestamp: Time;
    category: ListingCategory;
    price: bigint;
    location: string;
    condition: ListingCondition;
    images: Array<ExternalBlob>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Message {
    id: string;
    content: string;
    listingId: string;
    recipient: Principal;
    sender: Principal;
    timestamp: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
    isVerified: boolean;
    aadhaarHash: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ListingCategory {
    watches = "watches",
    earphones = "earphones",
    macbooks = "macbooks",
    phones = "phones"
}
export enum ListingCondition {
    new_ = "new",
    fair = "fair",
    good = "good",
    likeNew = "likeNew"
}
export enum PickupBookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createListing(listing: Listing): Promise<string>;
    deleteListing(listingId: string): Promise<void>;
    filterByCategory(category: ListingCategory): Promise<Array<Listing>>;
    filterByCondition(condition: ListingCondition): Promise<Array<Listing>>;
    filterByPriceRange(minPrice: bigint, maxPrice: bigint): Promise<Array<Listing>>;
    getAllListings(): Promise<Array<Listing>>;
    getAllListingsByPrice(): Promise<Array<Listing>>;
    getAllMessages(): Promise<Array<Message>>;
    getAllPickupBookings(): Promise<Array<PickupBooking>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getCallerMessagesWithUser(user: Principal): Promise<Array<Message>>;
    getCallerRelatedListings(): Promise<Array<Listing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getListingById(listingId: string): Promise<Listing | null>;
    getMessagesForListing(listingId: string): Promise<Array<Message>>;
    getPickupBooking(bookingId: string): Promise<PickupBooking | null>;
    getPickupsByDate(date: string): Promise<Array<PickupBooking>>;
    getPickupsByStatus(status: PickupBookingStatus): Promise<Array<PickupBooking>>;
    getPickupsByTimeSlot(timeSlot: string): Promise<Array<PickupBooking>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    postMessage(listingId: string, recipient: Principal, content: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchListings(searchText: string): Promise<Array<Listing>>;
    submitPickupBooking(booking: PickupBooking): Promise<string>;
    updateBookingStatus(bookingId: string, newStatus: PickupBookingStatus): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, Listing as _Listing, ListingCategory as _ListingCategory, ListingCondition as _ListingCondition, PickupBooking as _PickupBooking, PickupBookingStatus as _PickupBookingStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createListing(arg0: Listing): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(await to_candid_Listing_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(await to_candid_Listing_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async filterByCategory(arg0: ListingCategory): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByCategory(to_candid_ListingCategory_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByCategory(to_candid_ListingCategory_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterByCondition(arg0: ListingCondition): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByCondition(to_candid_ListingCondition_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByCondition(to_candid_ListingCondition_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterByPriceRange(arg0: bigint, arg1: bigint): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByPriceRange(arg0, arg1);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByPriceRange(arg0, arg1);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllListingsByPrice(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListingsByPrice();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListingsByPrice();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessages();
            return result;
        }
    }
    async getAllPickupBookings(): Promise<Array<PickupBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPickupBookings();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPickupBookings();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getCallerMessagesWithUser(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerMessagesWithUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerMessagesWithUser(arg0);
            return result;
        }
    }
    async getCallerRelatedListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRelatedListings();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRelatedListings();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingById(arg0: string): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingById(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingById(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesForListing(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesForListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesForListing(arg0);
            return result;
        }
    }
    async getPickupBooking(arg0: string): Promise<PickupBooking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPickupBooking(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPickupBooking(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPickupsByDate(arg0: string): Promise<Array<PickupBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPickupsByDate(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPickupsByDate(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPickupsByStatus(arg0: PickupBookingStatus): Promise<Array<PickupBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPickupsByStatus(to_candid_PickupBookingStatus_n37(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPickupsByStatus(to_candid_PickupBookingStatus_n37(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPickupsByTimeSlot(arg0: string): Promise<Array<PickupBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPickupsByTimeSlot(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPickupsByTimeSlot(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async postMessage(arg0: string, arg1: Principal, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.postMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchListings(arg0: string): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitPickupBooking(arg0: PickupBooking): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPickupBooking(to_candid_PickupBooking_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPickupBooking(to_candid_PickupBooking_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBookingStatus(arg0: string, arg1: PickupBookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_PickupBookingStatus_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_PickupBookingStatus_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ListingCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingCategory): ListingCategory {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ListingCondition_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingCondition): ListingCondition {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_Listing_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Promise<Listing> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PickupBookingStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickupBookingStatus): PickupBookingStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PickupBooking_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickupBooking): PickupBooking {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Promise<Listing | null> {
    return value.length === 0 ? null : await from_candid_Listing_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PickupBooking]): PickupBooking | null {
    return value.length === 0 ? null : from_candid_PickupBooking_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    seller: Principal;
    timestamp: _Time;
    category: _ListingCategory;
    price: bigint;
    location: string;
    condition: _ListingCondition;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    title: string;
    description: string;
    seller: Principal;
    timestamp: Time;
    category: ListingCategory;
    price: bigint;
    location: string;
    condition: ListingCondition;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        seller: value.seller,
        timestamp: value.timestamp,
        category: from_candid_ListingCategory_n21(_uploadFile, _downloadFile, value.category),
        price: value.price,
        location: value.location,
        condition: from_candid_ListingCondition_n23(_uploadFile, _downloadFile, value.condition),
        images: await from_candid_vec_n25(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PickupBookingStatus;
    date: string;
    sellerName: string;
    address: string;
    timestamp: _Time;
    phone: string;
    quotedPrice: bigint;
    timeSlot: string;
    deviceModel: string;
}): {
    id: string;
    status: PickupBookingStatus;
    date: string;
    sellerName: string;
    address: string;
    timestamp: Time;
    phone: string;
    quotedPrice: bigint;
    timeSlot: string;
    deviceModel: string;
} {
    return {
        id: value.id,
        status: from_candid_PickupBookingStatus_n30(_uploadFile, _downloadFile, value.status),
        date: value.date,
        sellerName: value.sellerName,
        address: value.address,
        timestamp: value.timestamp,
        phone: value.phone,
        quotedPrice: value.quotedPrice,
        timeSlot: value.timeSlot,
        deviceModel: value.deviceModel
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    watches: null;
} | {
    earphones: null;
} | {
    macbooks: null;
} | {
    phones: null;
}): ListingCategory {
    return "watches" in value ? ListingCategory.watches : "earphones" in value ? ListingCategory.earphones : "macbooks" in value ? ListingCategory.macbooks : "phones" in value ? ListingCategory.phones : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    fair: null;
} | {
    good: null;
} | {
    likeNew: null;
}): ListingCondition {
    return "new" in value ? ListingCondition.new : "fair" in value ? ListingCondition.fair : "good" in value ? ListingCondition.good : "likeNew" in value ? ListingCondition.likeNew : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): PickupBookingStatus {
    return "cancelled" in value ? PickupBookingStatus.cancelled : "pending" in value ? PickupBookingStatus.pending : "completed" in value ? PickupBookingStatus.completed : "confirmed" in value ? PickupBookingStatus.confirmed : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Promise<Array<Listing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Listing_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PickupBooking>): Array<PickupBooking> {
    return value.map((x)=>from_candid_PickupBooking_n28(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ListingCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCategory): _ListingCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ListingCondition_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCondition): _ListingCondition {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_Listing_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Listing): Promise<_Listing> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PickupBookingStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PickupBookingStatus): _PickupBookingStatus {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_PickupBooking_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PickupBooking): _PickupBooking {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    seller: Principal;
    timestamp: Time;
    category: ListingCategory;
    price: bigint;
    location: string;
    condition: ListingCondition;
    images: Array<ExternalBlob>;
}): Promise<{
    id: string;
    title: string;
    description: string;
    seller: Principal;
    timestamp: _Time;
    category: _ListingCategory;
    price: bigint;
    location: string;
    condition: _ListingCondition;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        seller: value.seller,
        timestamp: value.timestamp,
        category: to_candid_ListingCategory_n12(_uploadFile, _downloadFile, value.category),
        price: value.price,
        location: value.location,
        condition: to_candid_ListingCondition_n14(_uploadFile, _downloadFile, value.condition),
        images: await to_candid_vec_n16(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: PickupBookingStatus;
    date: string;
    sellerName: string;
    address: string;
    timestamp: Time;
    phone: string;
    quotedPrice: bigint;
    timeSlot: string;
    deviceModel: string;
}): {
    id: string;
    status: _PickupBookingStatus;
    date: string;
    sellerName: string;
    address: string;
    timestamp: _Time;
    phone: string;
    quotedPrice: bigint;
    timeSlot: string;
    deviceModel: string;
} {
    return {
        id: value.id,
        status: to_candid_PickupBookingStatus_n37(_uploadFile, _downloadFile, value.status),
        date: value.date,
        sellerName: value.sellerName,
        address: value.address,
        timestamp: value.timestamp,
        phone: value.phone,
        quotedPrice: value.quotedPrice,
        timeSlot: value.timeSlot,
        deviceModel: value.deviceModel
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCategory): {
    watches: null;
} | {
    earphones: null;
} | {
    macbooks: null;
} | {
    phones: null;
} {
    return value == ListingCategory.watches ? {
        watches: null
    } : value == ListingCategory.earphones ? {
        earphones: null
    } : value == ListingCategory.macbooks ? {
        macbooks: null
    } : value == ListingCategory.phones ? {
        phones: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCondition): {
    new: null;
} | {
    fair: null;
} | {
    good: null;
} | {
    likeNew: null;
} {
    return value == ListingCondition.new ? {
        new_: null
    } : value == ListingCondition.fair ? {
        fair: null
    } : value == ListingCondition.good ? {
        good: null
    } : value == ListingCondition.likeNew ? {
        likeNew: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PickupBookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == PickupBookingStatus.cancelled ? {
        cancelled: null
    } : value == PickupBookingStatus.pending ? {
        pending: null
    } : value == PickupBookingStatus.completed ? {
        completed: null
    } : value == PickupBookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
